name: Docker Image CI

on:
  workflow_run:
      workflows: ["Build"]
      types:
        - completed

jobs:

  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
